/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/earth.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        position={[-80, 30, -100]}
        scale={[0.07, 0.07, 0.07]}
        material={materials["Default OBJ"]}
        geometry={nodes.Cube001.geometry}
      />
    </group>
  );
}

useGLTF.preload("/earth.glb");
