/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/police.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.kt_facebuilder_material}
        geometry={nodes.FaceBuilderHead.geometry}
        position={[0, 18.31, 0]}
        scale={[2.1, 2.1, 2.1]}
      />
      <mesh material={materials['m158_body.001']} geometry={nodes.Mesh001.geometry} />
      <mesh material={materials['m158_head.001']} geometry={nodes.Mesh001_1.geometry} />
      <mesh material={materials['m158_helmet.001']} geometry={nodes.Mesh001_2.geometry} />
      <mesh material={materials['m158_equipment.001']} geometry={nodes.Mesh001_3.geometry} />
      <mesh material={materials['m158_pistol.001']} geometry={nodes.Mesh001_4.geometry} />
      <mesh material={materials['m158_opacity.001']} geometry={nodes.Mesh001_5.geometry} />
    </group>
  )
}

useGLTF.preload('/police.glb')
